# 現在地からの最大距離 (LY)
max_dist = 600.0

# 古さの下限
days = 700

# 表示する行数
max_entries = 24

# 対象とする項目
# information : ステーションの基本情報
# market      : コモディティの市場情報
# shipyard    : シップヤードの情報
# outfitting  : パーツの情報
information = true
market = true
shipyard = true
outfitting = true

# 動作モード
#   oneshot : 1回実行して終了
#   update  : 自動更新
mode = "update"

# 距離計算の起点
#   current : 現在位置
#   Sol     : Sol
pos_origin = "current"

# 除外対象とする星系名の正規表現
exclude_systems = []

# 除外対象とするステーション名の正規表現
# 救助船の古いエントリが残っているため、除外している
excludes = ["^Rescue Ship - "]