# 現在地からの最大距離
max_dist = 600.0

# 古さの下限
days = 700

# 表示する行数
max_entries = 24

# 動作モード
#   oneshot : 1回実行して終了
#   update  : 自動更新
mode = "update"

# 除外対象とする星系名の正規表現
exclude_systems = []

# 除外対象とするステーション名の正規表現
# 救助船の古いエントリが残っているため、除外している
excludes = ["^Rescue Ship - "]