# 現在地からの最大距離
max_dist = 600.0

# 表示する行数
max_entries = 24

# 動作モード
#   oneshot : 1回実行して終了
#   update  : 自動更新
mode = "update"

# 距離計算の起点
#   current : 現在位置
#   Sol     : Sol
pos_origin = "current"


# 対象とする項目と基準となる古さ（日）
# information : ステーションの基本情報
# market      : コモディティの市場情報
# shipyard    : シップヤードの情報
# outfitting  : パーツの情報
[days]
information = 700
market = 700
shipyard = 700
outfitting = 700

# フィルタ設定
[filter]
# 除外対象とする星系名の正規表現
# 正規表現の仕様は https://docs.rs/regex/1.3.1/regex/ を参照
exclude_systems = []

# 除外対象とするステーション名の正規表現
exclude_names = []

# # 星系内の最大距離
# [filter.distance_to_arrival]
# max = 1000.0

# # ステーションの産業の指定
# [filter.economy]
# list = ["Refinery"]
# include_secondary = false

# # パッドサイズの指定
# [filter.pad_size]
# l_pad_only = true

# # 地上基地を含むか
# [filter.planetary]
# include = false
